### ISSUE TITLE
Post Updates handled as new posts

### ISSUE THREAD

**Issue by josephsavage** [holgern/steembasicincome#11]
Updates on older posts are being handled as though they were new. This negatively impacts comment voting triggers.

Example: 
https://steemd.com/palnet/@felipejoys/ultimate-new-user-guide

Post was created on 7/18 but updated on 8/4. When the post updated, it overwrote last_post for member and triggered comment_upvote flag because post was older than 7 days.

Likely solution:
store_member_hist needs to skip posts were last_update is more than one day more recent than created.

**Comment by Rishi556** [comment]
Don't know how beem returns posts or anything but here's how I would do it.

https://github.com/holgern/steembasicincome/blob/81637cae42e5517608c714429c2b5f70d90a60e9/sbi_stream_post_comment.py#L178

Maybe change that line to 
`if main_post and c["created"] == c["last_update] :`

Not very familiar with beem and its been over a year since I wrote some useful python though.

**Comment by Rishi556** [comment]
Don't know how beem returns posts or anything but here's how I would do it.

Change
https://github.com/holgern/steembasicincome/blob/81637cae42e5517608c714429c2b5f70d90a60e9/sbi_stream_post_comment.py#L178-L180 to

```python
if main_post:
    if c["created"] == c["last_update] :
        member_data[ops["author"]]["last_post"] = c["created"]
        member_data[ops["author"]]["comment_upvote"] = 0
```
Not very familiar with beem and it's been over a year since I wrote some useful python so please check this over.

#12

**Comment by holgern** [comment]
Fixed
